Initial local commit - overwrite remote

diff --git a/openmediavault/debian/openmediavault.postinst b/openmediavault/debian/openmediavault.postinst
--- a/openmediavault/debian/openmediavault.postinst
+++ b/openmediavault/debian/openmediavault.postinst
@@ -195,6 +195,8 @@ case "$1" in
 		deb-systemd-helper enable smartctl-hdparm.service
 
 		# Ensure all openmediavault systemd units are enabled.
+		deb-systemd-invoke unmask openmediavault-engined.service || :
+		deb-systemd-helper enable openmediavault-engined.service
 		deb-systemd-helper enable openmediavault-beep-up.service
 		deb-systemd-helper enable openmediavault-beep-down.service
 		deb-systemd-helper enable openmediavault-cleanup-monit.service
@@ -215,7 +217,13 @@ case "$1" in
 		omv-confdbadm create "conf"
 		if [ -n "$2" ]; then
 			echo "Migrating configuration database ..."
-			omv-confdbadm migrate "conf" "${2}"
+			# Extract version number from package string
+			version=$(echo "${2}" | sed -n 's/.*\([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
+			if [ -n "$version" ]; then
+				omv-confdbadm migrate "conf" "$version"
+			else
+				echo "Skipping migration due to invalid version format: ${2}"
+			fi
 		fi
 
 		########################################################################
